### ISSUE TITLE
pb_schema.json doesn't work on 0.23.0-rc13

### ISSUE THREAD

**Issue by frankdeno** [mrwyndham/pocketbase-lemonsqueezy#1]
Hola :wave:

doesn't work. 

![image](https://github.com/user-attachments/assets/f81a7a45-5f9f-41f6-907a-0b1eefb15792)

I assume it has to do with the latest version. 

No issue. But so you know. 

Cheers :v:

p.s. sry to lazy to make a good bug report^^ 

Update: Yes, it was the version. Downloaded the 0.22, imported it, delete 0.22, downloaded 0.23, works.

**Comment by mrwyndham** [comment]
Thanks for the report - I will be sure to update this once 0.23 is released! Closing for now but will provide it soon
